// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC50sv33r91sGRfBumNm2yPhw3bV_s3KKA',
    appId: '1:844113587574:web:91df044b10460051251e57',
    messagingSenderId: '844113587574',
    projectId: 'nanyscare-1456b',
    authDomain: 'nanyscare-1456b.firebaseapp.com',
    storageBucket: 'nanyscare-1456b.firebasestorage.app',
    measurementId: 'G-2TGQKLM8R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsDu9UvHJnm8cLb7RSCkjp9b8VuC6Q6eE',
    appId: '1:844113587574:android:de05c64df068ea3a251e57',
    messagingSenderId: '844113587574',
    projectId: 'nanyscare-1456b',
    storageBucket: 'nanyscare-1456b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZrk2S9Ajlc8aYDATgdHp_39mAs9soEQ',
    appId: '1:844113587574:ios:16baede93031a059251e57',
    messagingSenderId: '844113587574',
    projectId: 'nanyscare-1456b',
    storageBucket: 'nanyscare-1456b.firebasestorage.app',
    iosClientId: '844113587574-tvfue54ni680batisf5h95rqua6f4t7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgZrk2S9Ajlc8aYDATgdHp_39mAs9soEQ',
    appId: '1:844113587574:ios:f09f5b1f4867bd95251e57',
    messagingSenderId: '844113587574',
    projectId: 'nanyscare-1456b',
    storageBucket: 'nanyscare-1456b.firebasestorage.app',
    iosClientId: '844113587574-obu9189jlrebdgsfpj3i6u8lsrh02g9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanysCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC50sv33r91sGRfBumNm2yPhw3bV_s3KKA',
    appId: '1:844113587574:web:c0c7927e97463a28251e57',
    messagingSenderId: '844113587574',
    projectId: 'nanyscare-1456b',
    authDomain: 'nanyscare-1456b.firebaseapp.com',
    storageBucket: 'nanyscare-1456b.firebasestorage.app',
    measurementId: 'G-K3Z2N4E96Y',
  );
}
